### ISSUE TITLE
Offline players

### ISSUE THREAD

**Issue by Barnaby-H** [LuckPerms/placeholders#15]
There is an easy way to implement the placeholders of offline players. Please implement it, it has been requested 5 times in a day on the discord server.
https://www.spigotmc.org/resources/placeholderapi.6245/update?update=229457
Many thanks.

**Comment by lucko** [comment]
Due to the nature of the way LuckPerms handles data storage, it is not possible to implement placeholder lookups for OfflinePlayers unless PlaceholderAPI added the concept of an async placeholder.

(it is for this same reason that LP does not support Vault lookups for offline players by default unless the lookup request is made asynchronously via the scheduler)
